- hosts: localhost
  connection: local
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/node-setup.yml
    - import_tasks: tasks/npm-packages.yml
    - import_tasks: tasks/zsh-setup.yml
    - import_tasks: tasks/productivity-tools.yml
    - import_tasks: tasks/nvim-setup.yml
    - import_tasks: tasks/lsp.yml
    - import_tasks: tasks/dotfiles.yml
